/**
 * 由 CoCo 源代码计划解包器解包
 *
 * 模块 ID：169
 */

"use strict"

var n
!function (t) {
  t[t.OTHER = 0] = "OTHER"
  t[t.ORIENTATION = 1] = "ORIENTATION"
  t[t.BYTE_SEGMENTS = 2] = "BYTE_SEGMENTS"
  t[t.ERROR_CORRECTION_LEVEL = 3] = "ERROR_CORRECTION_LEVEL"
  t[t.ISSUE_NUMBER = 4] = "ISSUE_NUMBER"
  t[t.SUGGESTED_PRICE = 5] = "SUGGESTED_PRICE"
  t[t.POSSIBLE_COUNTRY = 6] = "POSSIBLE_COUNTRY"
  t[t.UPC_EAN_EXTENSION = 7] = "UPC_EAN_EXTENSION"
  t[t.PDF417_EXTRA_METADATA = 8] = "PDF417_EXTRA_METADATA"
  t[t.STRUCTURED_APPEND_SEQUENCE = 9] = "STRUCTURED_APPEND_SEQUENCE"
  t[t.STRUCTURED_APPEND_PARITY = 10] = "STRUCTURED_APPEND_PARITY"
}(n || (n = {}))
exports.a = n
