/** 
 * 由 CoCo 源代码计划解包器解包
 *
 * 模块 ID：4/1v
 */

// removed by extract-text-webpack-plugin
module.exports = {
  "home": "home_1xbqQ",
  "createBox": "createBox_PB_-m",
  "shadow": "shadow_ycmQR",
  "createItem": "createItem_1KsCZ",
  "createIcon": "createIcon_x6U2x",
  "disabled": "disabled_2Sn3u",
  "tips": "tips_pYykR",
  "center": "center_1aavX",
  "newUser": "newUser_3Z-0i",
  "hide": "hide_39nn3",
  "bannerBox": "bannerBox_yjTIz",
  "bannerItem": "bannerItem_lhLlK",
  "image": "image_3jclR",
  "bannerPrev": "bannerPrev_2REHI",
  "bannerNext": "bannerNext_38HvL",
  "noticeBox": "noticeBox_eQSRQ",
  "noticeItem": "noticeItem_UFh5j",
  "noticeChar": "noticeChar_3P7Jj",
  "courseBox": "courseBox_3gdMf",
  "hidden": "hidden_201b7",
  "titleBox": "titleBox_1AEl8",
  "title": "title_1mlu1",
  "checkbox": "checkbox_3yG0X",
  "checked": "checked_2M8lj",
  "finish": "finish_ej17M",
  "courseList": "courseList_215BE",
  "courseItem": "courseItem_135NY",
  "courseImage": "courseImage_2Z-eL",
  "mask": "mask_2f1Hl",
  "playBox": "playBox_3_NJM",
  "courseName": "courseName_F8WpN",
  "courseDesc": "courseDesc_9ST8E",
  "animation": "animation_YwdJn",
  "hideCourseBoxAnimation": "hideCourseBoxAnimation_2iIFs",
  "newUserTemplate": "newUserTemplate_1t7u4",
  "templateTitle": "templateTitle_Z-eQ0",
  "titleIcon": "titleIcon_1ZB5-",
  "templateList": "templateList_dJG4l",
  "templateItem": "templateItem_31rRK",
  "imageBox": "imageBox_1Sg6U",
  "gif": "gif_8urEH",
  "name": "name_rmN6Y",
  "desc": "desc_bPS_9",
  "previewBtn": "previewBtn_29W78",
  "blue": "blue_2-_D2",
  "yellow": "yellow_2y7v0",
  "purple": "purple_31Wxx",
  "myWork": "myWork_KP39x",
  "workList": "workList_1nAUt",
  "workListNoData": "workListNoData_2V3p8",
  "createBtn": "createBtn_2QN5x",
  "icon": "icon_3YAn5",
  "oldUserTemplate": "oldUserTemplate_1-Xwf",
  "pageBtn": "pageBtn_2D8If",
  "btnItem": "btnItem_2hfoj",
  "prev": "prev_1spBZ",
  "startWork": "startWork_msqmn",
  "startBtn": "startBtn_1BREu",
  "startIcon": "startIcon_2wi8o",
  "startIconAnimation": "startIconAnimation_YBc83"
}

/***/
