"use strict";

/* harmony export (binding) */
export { tw };
var tw = {
  'sign_in_dialog/error/password_confirm/not_same': '兩次輸入的密碼不一致，請重新輸入',
  'sign_in_dialog/error/phone/unregisterd': '手機號未註冊，',
  'sign_in_dialog/error/other/acc_or_pwd': '用戶名或密碼不正確',
  'sign_in_dialog/error/phone/registered': '手機號已註冊，',
  'sign_in_dialog/error/phone/format': '手機格式不正確',
  'sign_in_dialog/error/password/format': '請輸入6-20位密碼',
  'sign_in_dialog/error/sms_code/fail': '驗證碼錯誤，請重新輸入',
  'sign_in_dialog/error/email/empty': '郵箱不能為空',
  'sign_in_dialog/error/email/exist': '註冊失敗，帳號已經存在',
  'sign_in_dialog/error/email/not_exist': '帳號不存在，請輸入已註冊的郵箱',
  'sign_in_dialog/error/email/format': '郵箱格式不正確',
  'sign_in_dialog/error/email/email_often': '郵件發送過於頻繁',
  'sign_in_dialog/error/email/send_exceed_limit': '今天重置密碼發送郵件已達上限',
  'sign_in_dialog/error/other/network': '網絡連接出錯了,請稍後再試',
  'sign_in_dialog/verify_email/email_title': '驗證郵件已發出',
  'sign_in_dialog/verify_email/email_success_content_1': '請在24小時內登入郵箱',
  'sign_in_dialog/verify_email/email_success_content_2': '並按郵件提示進行操作完成驗證',
  'sign_in_dialog/placeholder/username': '手機/郵箱/用戶名',
  'sign_in_dialog/placeholder/email': '郵箱',
  'sign_in_dialog/placeholder/password': '密碼',
  'sign_in_dialog/placeholder/code': '驗證碼',
  'sign_in_dialog/placeholder/password_n_tip': '密碼（6-20位）',
  'sign_in_dialog/placeholder/password_confirm': '再次輸入密碼',
  'sign_in_dialog/placeholder/mobile_phone': '手機',
  'sign_in_dialog/login': '登錄',
  'sign_in_dialog/register': '註冊',
  'sign_in_dialog/btn_code': '獲取驗證碼',
  'sign_in_dialog/login_now': '立即登錄',
  'sign_in_dialog/register_now': '立即註冊',
  'sign_in_dialog/create_account': '立即註冊',
  'sign_in_dialog/sign_in_with_password': '密碼登錄',
  'sign_in_dialog/sign_in_with_sms': '短信登錄',
  'sign_in_dialog/find_password': '找回密碼',
  'sign_in_dialog/sign_up_account': '賬號註冊',
  'sign_in_dialog/new_user_sign_up': '新用戶註冊',
  'sign_in_dialog/back_to_login': '返回登錄',
  'sign_in_dialog/reset_password': '重置密碼',
  'sign_in_dialog/finish': '完成',
  'sign_in_dialog/forget_password/verify': '驗證身份後，可重置密碼',
  'sign_in_dialog/next': '下一步',
  'sign_in_dialog/forget_password/success': '密碼重置成功',
  'sign_in_dialog/forget_password/entry': '忘記密碼？',
  'sign_in_dialog/already_has_account': '已經有賬號了？去登錄！',
  'sign_in_dialog/register/confirm': '確定'
};

/***/