"use strict";

export { r as i };
export { o as h };
export { i as g };
export { a as f };
export { s as a };
export { c };
export { l as b };
export { u as e };
export { d };
var r = 40;
var o = 40;
var i = 1800;
var a = 3200;
var s = "#FFFFFFFF";
var c = 300;
var l = 300;
var u = !1;
var d = !1;