"use strict";

export { r as a };
export { o as c };
export { i as e };
export { a as g };
export { s as i };
export { c as h };
export { l as b };
export { u as f };
export { d };
var r = "#5DC5FBFF";
var o = 3;
var i = 50;
var a = 1;
var s = !1;
var c = !1;
var l = 30;
var u = 0;
var d = 9999;
export default r;