module.exports = {
  hide: "ConsolePanel_hide__ema1i",
  container: "ConsolePanel_container__sYMKI",
  main: "ConsolePanel_main__1posf",
  active: "ConsolePanel_active__2mOPe",
  header: "ConsolePanel_header__WFXUe",
  title: "ConsolePanel_title__3ehUV",
  errorCount: "ConsolePanel_errorCount__1oIc2",
  right: "ConsolePanel_right__3sndR",
  filterIcon: "ConsolePanel_filterIcon__3FiHc",
  clearIcon: "ConsolePanel_clearIcon__8NShj",
  closeIcon: "ConsolePanel_closeIcon__2aAZJ",
  filterCategory: "ConsolePanel_filterCategory__2DIQk",
  filterItem: "ConsolePanel_filterItem__CcTjk",
  iconBox: "ConsolePanel_iconBox__30b8P",
  miniContainer: "ConsolePanel_miniContainer__3mzwH",
  errorIcon: "ConsolePanel_errorIcon__2JdB8",
  warnIcon: "ConsolePanel_warnIcon__8XnOJ",
  iconBg: "ConsolePanel_iconBg__2JvCD",
  errorWarningBreath: "ConsolePanel_errorWarningBreath__333R0",
  errorBreathe: "ConsolePanel_errorBreathe__36tzM",
  warningBreathe: "ConsolePanel_warningBreathe__3pVsh",
  errorBreath: "ConsolePanel_errorBreath__2eeu5",
  warningBreath: "ConsolePanel_warningBreath__1I76L"
};