module.exports = {
  container: "style_container__Wb2Q8",
  fadeIn: "style_fadeIn__2YzYL",
  dialog: "style_dialog__1hz_q",
  popOut: "style_popOut__1qgbY",
  singleElementContentBox: "style_singleElementContentBox__SIda2",
  imageBox: "style_imageBox__t6mrP",
  contentBox: "style_contentBox__1sOIN",
  title: "style_title__2Kzwy",
  textBox: "style_textBox__3IZO2",
  inputBox: "style_inputBox__2KyzX",
  text: "style_text__3-avq",
  button: "style_button__3bezl",
  buttonBox: "style_buttonBox__QpwfR",
  cancelButton: "style_cancelButton__uMRLg",
  mainButton: "style_mainButton__FPOqc",
  optionButtonBox: "style_optionButtonBox__2hGB_",
  dialogInput: "style_dialogInput__1sPsX",
  styleA: "style_styleA__2Do3I",
  styleB: "style_styleB__RrE_U"
};