import path from "path"
import { unpack, SetPath } from "./core"

const distPath: string = path.resolve("public", "creation.codemao.cn", "coco", "home", "dist")

unpack({
    entry: [
        path.resolve(distPath, "commons.abcbc2e5b889aff92f60.js"),
        path.resolve(distPath, "coco.68b628c42c02a09917c6.js"),
        path.resolve(distPath, "work.8bf5adc29b1d512720c7.js")
    ],
    externals: [
        {
            searchPath: /^react$/,
            replace: "react"
        }, {
            searchPath: /^react\/dom$/,
            replace: "react-dom"
        }, {
            searchPath: /^react\/redux$/,
            replace: "react-redux"
        }, {
            searchPath: /^react\/intl$/,
            replace: "react-intl"
        }, {
            searchPath: /^react\/draggable$/,
            replace: "react-draggable"
        }, {
            searchPath: /^(.*\/)?react\/three\/fiber$/,
            replace: "@react-three/fiber"
        }, {
            searchPath: /^react\/router(\/index)?$/,
            replace: "react-router"
        }, {
            searchPath: /^react\/router\/dom$/,
            replace: "react-router-dom"
        }, {
            searchPath: /^react\/loadable$/,
            replace: "react-loadable"
        }, {
            searchPath: /^react\/css\/modules$/,
            replace: "react-css-modules"
        }, {
            searchPath: /^lodash\//,
            replace: "lodash/"
        }, {
            searchPath: /^(.*\/)?ant\/design\/icons\/.*$/,
            replace: "@ant-design/icons"
        }, {
            searchPath: /^(.*\/)?ant\/design\/react\/.*$/,
            replace: "@ant-design/react-slick"
        }, {
            searchPath: /^antd(\/.*)?$/,
            replace: "antd"
        }, {
            searchPath: /^(.*\/)?babel\/runtime\//,
            replace: "@babel/runtime/"
        }, {
            searchPath: /^babel\/plugin\/react\/css\/modules\//,
            replace: "babel-plugin-react-css-modules/"
        }, {
            searchPath: /^babel\/polyfill.*$/,
            replace: "babel-polyfill"
        }, {
            searchPath: /^video\/react$/,
            replace: "video-react"
        }, {
            searchPath: /^sa\/sdk\/javascript$/,
            replace: "sa-sdk-javascript"
        }, {
            searchPath: /^intl$/,
            replace: "intl"
        }, {
            searchPath: /^axios$/,
            replace: "axios"
        }, {
            searchPath: /^shortid$/,
            replace: "shortid"
        }, {
            searchPath: /^redux$/,
            replace: "redux"
        }, {
            searchPath: /^redux\/actions$/,
            replace: "redux-actions"
        }, {
            searchPath: /^redux\/saga$/,
            replace: "redux-saga"
        }, {
            searchPath: /^redux\/saga\/effects$/,
            replace: "redux-saga/effects"
        }, {
            searchPath: /^classnames$/,
            replace: "classnames"
        }, {
            searchPath: /^build\/three\/module$/,
            replace: "three"
        }, {
            searchPath: /^three\/examples/,
            replace: "three/examples"
        }, {
            searchPath: /^invariant$/,
            replace: "invariant"
        }
    ],
    output: {
        basePath: process.cwd(),
        unrestoredPath: "unrestored/home",
        srcPath: "src",
        srcUnrestoredPath: "src-unrestored"
    },
    publicPath: "https://creation.codemao.cn/coco/home/dist/",
    setPath: SetPath.BY_IMPORT_NAME,
    moveToSrc: {
        0: ".",
        "q9Rd": "/home/redux/store",
        "2V4L": "/home/redux/selectors",
        "faTg": "/home/redux/main/interface",
        "/FmP": "/home/redux/main/actions",
        "KBfb": "/home/redux/main/reducer",
        "ePvC": "/home/redux/main/saga",
        "qMEF": "/home/ui/app",
        "sEiI": "/home/ui/components/Header/index",
        "G1ZB": "/home/ui/components/Header/template",
        "ZbQe": "/home/ui/components/Header/styles.module.css",
        "sdA1": "/home/ui/components/Menu/index",
        "My5k": "/home/ui/components/Menu/template",
        "HR1v": "/home/ui/components/Menu/styles.module.css",
        "EPod": "/home/ui/routes/index",
        "Y/qu": "/home/ui/routes/template",
        "hCpk": "/home/ui/routes/Home/index",
        "+DtV": "/home/ui/routes/Home/template",
        "4/1v": "/home/ui/routes/Home/styles.module.css",
        "vDhS": "/home/ui/routes/Home/model/interface",
        "twBc": "/home/ui/routes/Home/model/actions",
        "eHP9": "/home/ui/routes/Home/model/reducer",
        "TNoC": "/home/ui/routes/Home/model/saga",
        "Pv6Z": "/home/ui/routes/Work/index",
        "7CtK": "/home/ui/routes/Work/template",
        "BDY2": "/home/ui/routes/Work/styles.module.css",
        "hC2z": "/home/ui/routes/Work/model/interface",
        "HXaG": "/home/ui/routes/Work/model/actions",
        "2PC+": "/home/ui/routes/Work/model/reducer",
        "BmOz": "/home/ui/routes/Work/model/saga",
        "YqO9": "/home/ui/components/Input/index",
        "FSbX": "/home/ui/components/WorkItem/index",
        "P9xH": "/home/ui/components/WorkItem/template",
        "Goqg": "/home/ui/components/WorkItem/styles.module.css",
        "IzpB": "/home/ui/components/Input/styles.module.css",
        "inl5": "/home/utils/uploader",
        "Slns": "/home/utils/cmao-cdn-uploader"
    },
    nodePolyfill: {
        "3IRH": "module",
        "f1Eh": "module",
        "DuR2": "global",
        "W2nU": "process"
    }
})
