"use strict";

export { r as h };
export { o as g };
export { i as d };
export { a as l };
export { s as k };
export { c as j };
export { l as i };
export { u as c };
export { d as b };
export { p as a };
export { f };
export { h as e };
var r = "icon-widget-date-picker";
var o = 202;
var i = 36;
var a = 155;
var s = 30;
var c = 360;
var l = 640;
var u = 16;
var d = "#111111ff";
var p = "#e4f5ffff";
var f = false;
var h = false;
export default p;