/**
 * 由 CoCo 源代码计划解包器解包
 *
 * 模块 ID：122
 */

"use strict"

var r
!function (t) {
  t[t.OTHER = 0] = "OTHER"
  t[t.PURE_BARCODE = 1] = "PURE_BARCODE"
  t[t.POSSIBLE_FORMATS = 2] = "POSSIBLE_FORMATS"
  t[t.TRY_HARDER = 3] = "TRY_HARDER"
  t[t.CHARACTER_SET = 4] = "CHARACTER_SET"
  t[t.ALLOWED_LENGTHS = 5] = "ALLOWED_LENGTHS"
  t[t.ASSUME_CODE_39_CHECK_DIGIT = 6] = "ASSUME_CODE_39_CHECK_DIGIT"
  t[t.ASSUME_GS1 = 7] = "ASSUME_GS1"
  t[t.RETURN_CODABAR_START_END = 8] = "RETURN_CODABAR_START_END"
  t[t.NEED_RESULT_POINT_CALLBACK = 9] = "NEED_RESULT_POINT_CALLBACK"
  t[t.ALLOWED_EAN_EXTENSIONS = 10] = "ALLOWED_EAN_EXTENSIONS"
}(r || (r = {}))
exports.a = r
