"use strict";

import * as r from "./2634/index";
var i = r.FLIPPED_ALIAS_KEYS.Standardized;
export { i as STANDARDIZED_TYPES };
var a = r.FLIPPED_ALIAS_KEYS.Expression;
export { a as EXPRESSION_TYPES };
var s = r.FLIPPED_ALIAS_KEYS.Binary;
export { s as BINARY_TYPES };
var o = r.FLIPPED_ALIAS_KEYS.Scopable;
export { o as SCOPABLE_TYPES };
var l = r.FLIPPED_ALIAS_KEYS.BlockParent;
export { l as BLOCKPARENT_TYPES };
var u = r.FLIPPED_ALIAS_KEYS.Block;
export { u as BLOCK_TYPES };
var c = r.FLIPPED_ALIAS_KEYS.Statement;
export { c as STATEMENT_TYPES };
var p = r.FLIPPED_ALIAS_KEYS.Terminatorless;
export { p as TERMINATORLESS_TYPES };
var f = r.FLIPPED_ALIAS_KEYS.CompletionStatement;
export { f as COMPLETIONSTATEMENT_TYPES };
var d = r.FLIPPED_ALIAS_KEYS.Conditional;
export { d as CONDITIONAL_TYPES };
var h = r.FLIPPED_ALIAS_KEYS.Loop;
export { h as LOOP_TYPES };
var y = r.FLIPPED_ALIAS_KEYS.While;
export { y as WHILE_TYPES };
var m = r.FLIPPED_ALIAS_KEYS.ExpressionWrapper;
export { m as EXPRESSIONWRAPPER_TYPES };
var v = r.FLIPPED_ALIAS_KEYS.For;
export { v as FOR_TYPES };
var g = r.FLIPPED_ALIAS_KEYS.ForXStatement;
export { g as FORXSTATEMENT_TYPES };
var T = r.FLIPPED_ALIAS_KEYS.Function;
export { T as FUNCTION_TYPES };
var b = r.FLIPPED_ALIAS_KEYS.FunctionParent;
export { b as FUNCTIONPARENT_TYPES };
var S = r.FLIPPED_ALIAS_KEYS.Pureish;
export { S as PUREISH_TYPES };
var E = r.FLIPPED_ALIAS_KEYS.Declaration;
export { E as DECLARATION_TYPES };
var x = r.FLIPPED_ALIAS_KEYS.PatternLike;
export { x as PATTERNLIKE_TYPES };
var P = r.FLIPPED_ALIAS_KEYS.LVal;
export { P as LVAL_TYPES };
var A = r.FLIPPED_ALIAS_KEYS.TSEntityName;
export { A as TSENTITYNAME_TYPES };
var k = r.FLIPPED_ALIAS_KEYS.Literal;
export { k as LITERAL_TYPES };
var w = r.FLIPPED_ALIAS_KEYS.Immutable;
export { w as IMMUTABLE_TYPES };
var O = r.FLIPPED_ALIAS_KEYS.UserWhitespacable;
export { O as USERWHITESPACABLE_TYPES };
var C = r.FLIPPED_ALIAS_KEYS.Method;
export { C as METHOD_TYPES };
var I = r.FLIPPED_ALIAS_KEYS.ObjectMember;
export { I as OBJECTMEMBER_TYPES };
var N = r.FLIPPED_ALIAS_KEYS.Property;
export { N as PROPERTY_TYPES };
var _ = r.FLIPPED_ALIAS_KEYS.UnaryLike;
export { _ as UNARYLIKE_TYPES };
var D = r.FLIPPED_ALIAS_KEYS.Pattern;
export { D as PATTERN_TYPES };
var j = r.FLIPPED_ALIAS_KEYS.Class;
export { j as CLASS_TYPES };
var L = r.FLIPPED_ALIAS_KEYS.ModuleDeclaration;
export { L as MODULEDECLARATION_TYPES };
var M = r.FLIPPED_ALIAS_KEYS.ExportDeclaration;
export { M as EXPORTDECLARATION_TYPES };
var B = r.FLIPPED_ALIAS_KEYS.ModuleSpecifier;
export { B as MODULESPECIFIER_TYPES };
var F = r.FLIPPED_ALIAS_KEYS.Private;
export { F as PRIVATE_TYPES };
var R = r.FLIPPED_ALIAS_KEYS.Flow;
export { R as FLOW_TYPES };
var U = r.FLIPPED_ALIAS_KEYS.FlowType;
export { U as FLOWTYPE_TYPES };
var K = r.FLIPPED_ALIAS_KEYS.FlowBaseAnnotation;
export { K as FLOWBASEANNOTATION_TYPES };
var V = r.FLIPPED_ALIAS_KEYS.FlowDeclaration;
export { V as FLOWDECLARATION_TYPES };
var W = r.FLIPPED_ALIAS_KEYS.FlowPredicate;
export { W as FLOWPREDICATE_TYPES };
var Y = r.FLIPPED_ALIAS_KEYS.EnumBody;
export { Y as ENUMBODY_TYPES };
var H = r.FLIPPED_ALIAS_KEYS.EnumMember;
export { H as ENUMMEMBER_TYPES };
var q = r.FLIPPED_ALIAS_KEYS.JSX;
export { q as JSX_TYPES };
var J = r.FLIPPED_ALIAS_KEYS.Miscellaneous;
export { J as MISCELLANEOUS_TYPES };
var X = r.FLIPPED_ALIAS_KEYS.TypeScript;
export { X as TYPESCRIPT_TYPES };
var G = r.FLIPPED_ALIAS_KEYS.TSTypeElement;
export { G as TSTYPEELEMENT_TYPES };
var z = r.FLIPPED_ALIAS_KEYS.TSType;
export { z as TSTYPE_TYPES };
var $ = r.FLIPPED_ALIAS_KEYS.TSBaseType;
export { $ as TSBASETYPE_TYPES };